### ISSUE TITLE
Avoid stripping the input text

### ISSUE THREAD

**Issue by lcswillems** [stanfordnlp/python-stanford-corenlp#38] opened 2019-06-04 09:37 UTC
Hi,

If I do:
```
client = corenlp.CoreNLPClient(annotators=('tokenize', 'parse'))
client.annotate(" hi ")
```

I get:
```
text: "hi"
sentence {
  token {
    word: "hi"
    pos: "UH"
    value: "hi"
    before: ""
    after: ""
    originalText: "hi"
    beginChar: 0
    endChar: 2
    beginIndex: 0
    endIndex: 1
    tokenBeginIndex: 0
    tokenEndIndex: 1
    hasXmlContext: false
  }
...
```

The text is `hi` instead of ` hi `. How is it possible to make CoreNLP stop stripping the input text?

**Comment by arunchaganty** [comment] 2019-06-29 22:47
Hmm... what is the motivation for not stripping the whitespace?

Unfortunately the root cause of this problem is in the [CoreNLPServer](https://github.com/stanfordnlp/CoreNLP/blob/9d98c7bb20ecec718e7823b4535d048fd454cd34/src/edu/stanford/nlp/pipeline/StanfordCoreNLPServer.java#L316). Text sent to the server is trimmed out of abundance of caution for any whitespace added through the URL encoding/decoding process. It should be ok to simply not do this and the easiest way to do so would be through a local checkout of CoreNLP.

**Comment by lcswillems** [comment] 2019-07-01 07:32
Because there is no reason why CoreNLP would strip it... If I want to strip it, I do it. I may want to give it some text that is not stripped.

**Comment by manning** [comment] 2019-07-14 17:32
As @arunchaganty notes, the trimming was happening in the Java CoreNLPServer. But it seems to me that there is no good reason why we were doing this, and it is in principle wrong as @lcswillems notes. So, I've removed it. 🙂So, whenever we next make a CoreNLP release (probably end of (northern) summer) or if you cherrypick CoreNLP commit 082ed17b04bdb7ed1ae613916d713942f7c24dfb then this should be fixed.

**Closed as completed by manning** 2019-07-14 17:32 UTC

**Comment by lcswillems** [comment] 2019-07-15 08:10
That's great!! Thanks a lot! :)
